mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    shop_index,
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    OrdersExportView,
    LatestProductsFeed,
    UserOrdersListView,
    UserOrdersExportView,
)
from .api import (
    ProductViewSet,
    OrderViewSet,
)

app_name = 'shopapp'

routers = DefaultRouter()
routers.register('products', ProductViewSet)
routers.register('orders', OrderViewSet)

urlpatterns = [
    path('', shop_index, name='index'),
    path('api/', include(routers.urls)),
    path('products/', ProductListView.as_view(), name='product_list'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),
    path('products/latest/feed/', LatestProductsFeed(), name='product_feed'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/create/', OrderCreateView.as_view(), name='create_order'),
    path('orders/export/', OrdersExportView.as_view(), name='export_order'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('users/<int:user_id>/orders/', UserOrdersListView.as_view(), name='orders_by_user'),
    path('users/<int:user_id>/orders/export/', UserOrdersExportView.as_view(), name='export_orders_by_user'),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Product(models.Model):
    """
    Модель Product представляет сущность товара для продажи в интернет-магазине

    Перейти к модели заказа: :model:`shopapp.Order`
    """
    class Meta:
        ordering = ['price']
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=False)
    price = models.DecimalField(default=0, max_digits=9, decimal_places=2)
    discount = models.PositiveSmallIntegerField(
        default=0,
        validators=[MaxValueValidator(100)]
    )
    creation_time = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return f'Product {self.name!r} with id {self.pk}'

    def get_absolute_url(self):
        return reverse('shopapp:product_details', kwargs={'pk': self.pk})


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
    return 'products/product_{pk}/images/{filename}'.format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    """
    Модель ProductImage представляет изображение товара

    Модель продукта: :model:`shopapp.Product`
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)


class Order(models.Model):
    """
    Модель Order представляет сущность заказа в интернет-магазине

    Перейти к модели продукта: :model:`shopapp.Product`
    """
    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    delivery_address = models.TextField(blank=True, null=False)
    promocode = models.CharField(blank=True, max_length=8)
    creation_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

    def __str__(self) -> str:
        return f'Order №{self.pk} for {self.user}'

    def get_absolute_url(self):
        return reverse('shopapp:order_details', kwargs={'pk': self.pk})

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm delete order №{{ object.pk }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to delete order №{{ object.pk }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:order_list' %}">Return to the orders list</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Delete order</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order №{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order №{{ object.pk }} details</h1>
  <div>
    <div>Delivery address: <em>{{ object.delivery_address }}</em></div>
    <div>
      Products:
      <ol>
          {% for product in object.products.all %}
              <li>
                  <a href="{% url 'shopapp:product_details' pk=product.pk %}">
                      {{ product.name }}
                  </a>, ${{ product.price }}</li>
          {% empty %}
              Заказ оказался пуст
          {% endfor %}
      </ol>
    </div>
    <div>User: {{ object.user }}</div>
    <div>Promocode: <code>{{ object.promocode }}</code></div>
    <div>Creation time: <em>{{ object.creation_time }}</em></div>
  </div>

  <br>
  <div>
    <a href="{% url 'shopapp:order_update' pk=object.pk %}">Update this order info</a>
  </div>
  <div>
    <a href="{% url 'shopapp:order_delete' pk=object.pk %}">Delete this order</a>
  </div>
  <div>
    <a href="{% url 'shopapp:order_list' %}">Back to the orders list</a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create order
{% endblock %}

{% block body %}
  <h1>Create new order</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Create order!
    </button>
  </form>

  <div>
    <a href="{% url 'shopapp:order_list' %}">
      Click to return to the orders list
    </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list title
{% endblock %}

{% block body %}
    <h1>Список заказов:</h1>
    <div>
    <ul>
        {% for order in orders %}
            <li>
                <a href="{% url 'shopapp:order_details' pk=order.pk %}">
                    Заказ №{{ order.id }}
                </a> от {{ order.creation_time }}</li>
            <p>Заказчик: {{order.user }}</p>
            <br>
        {% empty %}
            Заказов не найдено
        {% endfor %}
    </ul>
    </div>

    <div>
        <a href="{% url 'shopapp:create_order' %}">
            Нажмите, чтобы создать новый заказ
        </a>
    </div>
    <div>
        <a href="{% url 'shopapp:export_order' %}">
            Экспортировать полную информацию о всех заказах в JSON
        </a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update order
{% endblock %}

{% block body %}
  <h1>Update order №{{ object.pk }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Update order!
    </button>
  </form>

  <div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
      Click to return to the order №{{ object.pk }}
    </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/orders_by_user_list.html
{% extends 'shopapp/base.html' %}
{% load cache %}

{% block title %}
    User №{{ owner.pk }}'s orders
{% endblock %}

{% block body %}
    {% if owner %}
    <h1>{{ owner.username }}'s orders</h1>
        {% cache 120 orders_list owner.pk %}
        <div>
            <ul>
                {% for order in orders_list %}
                    <li>
                        <a href="{% url 'shopapp:order_details' pk=order.pk %}">
                            Order №{{ order.id }}
                        </a>
                    </li>
                    <p>Delivery address: {{ order.delivery_address }}</p>
                    <p>Promocode used: <code>{{ order.promocode }}</code></p>
                    <p>Creation time: {{ order.creation_time }}</p>
                    <p>
                        Products:
                        <ol>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} -  <i>{{ product.price }}$</i></li>
                            {% empty %}
                                No products in this order
                            {% endfor %}
                        </ol>
                    </p>
                    <br>
                {% empty %}
                    <h2>{{ owner.username }} does not have any orders yet</h2>
                {% endfor %}
            </ul>
        </div>
        {% endcache %}
    <div>
        <a href="{% url 'myauth:profile_details' pk=profile_id %}">
            Detail info about {{ owner.username }}
        </a>
    </div>
    {% else %}
        Something went wrong, no users received
    {% endif %}

    <div>
        <a href="{% url 'shopapp:create_order' %}">
            Create new order
        </a>
    </div>
    <div>
        <a href="{% url 'myauth:profile_list' %}">
            Full users list
        </a>
    </div>
    <div>
        <a href="{% url 'shopapp:order_list' %}">
            Full orders list
        </a>
    </div>

{% endblock %}

mysite/shopapp/templates/shopapp/orders_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools-items %}
    {% load admin_urls %}
    <li>
        <a href="{% url 'admin:import_orders_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archive product {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_list' %}">Return to the products list</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      <button type="submit">Delete product</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% blocktranslate with product_pk=object.pk %}
    Product №{{ product_pk }} details
  {% endblocktranslate %}
{% endblock %}

{% block body %}
  {% blocktranslate with name=object.name pk=object.pk %}
    <h1>Product {{ name }} (№{{ pk }}) details</h1>
  {% endblocktranslate %}
  <div>
    <div>{% translate 'Description' %}: <em>{{ object.description }}</em></div>
    <div>{% translate 'Price' %}: {{ object.price }}</div>
    <div>{% translate 'Discount' %}: {{ object.discount }}%</div>
    <div>{% translate 'Creation time' %}: <em>{{ object.creation_time }}</em></div>
    <div>{% translate 'Archived' %}: {{ object.archived }}</div>
  </div>

  <h3>{% translate 'Product images' %}:</h3>
  <div>

    {% blocktranslate count images_amount=object.images.all|length %}
      {{ images_amount }} image is uploaded
    {% plural %}
      {{ images_amount }} images are uploaded
    {% endblocktranslate %}

    {% for img in object.images.all %}
      <div><img src="{{ img.image.url }}" alt="img.image.name" style="margin-top:50px"></div>
      {% if img.description %}
        <sub>-> {{ img.description }}</sub>
      {% endif %}
    {% endfor %}
  </div>

  <br>
  <br>
  <div>
    <a href="{% url 'shopapp:product_update' pk=object.pk %}">
      {% translate 'Update this product info' %}
    </a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_delete' pk=object.pk %}">
      {% translate 'Archive this product' %}
    </a>
  </div>
  <div>
    <a href="{% url 'shopapp:product_list' %}">
      {% translate 'See full products list' %}
    </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create new product</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Create product!
    </button>
  </form>

  <div>
    <a href="{% url 'shopapp:product_list' %}">
      Click to return to the products list
    </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list title' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products list' %}</h1>
    <div>
        <ul>
            {% for product in products %}
                <li>
                    <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a>
                    (${{ product.price }})
                </li>
                <sub>-> {{ product.description }}</sub>
            {% empty %}
                {% translate 'Products list is empty!' %}
            {% endfor %}
        </ul>
        {% blocktranslate count products_amount=products|length %}
            <p>Only one product is available.</p>
        {% plural %}
            <p>{{ products_amount }} products are available.</p>
        {% endblocktranslate %}
    </div>

    {% if perms.shopapp.add_product %}
        <div>
            <a href="{% url 'shopapp:create_product' %}">
                {% translate 'Click to create a new product' %}
            </a>
        </div>
    {% endif %}

{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product {{ object.name }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Update product!
    </button>
  </form>

  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}">
      Click to return to the product {{ object.name }}
    </a>
  </div>

{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Shop index title
{% endblock %}

{% block body %}
    <h1>Shop index body</h1>
    <h3>Доступные страницы:</h3>
    <ul>
    {% for name, link in page_urls.items %}
        <li><a href={{ link }}>{{ name }}</a></li>
    {% empty %}
        Нет доступных страниц :(
    {% endfor %}
    </ul>
{% endblock %}

mysite/shopapp/templates/shopapp/users_orders_export.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Export orders info
{% endblock %}

{% block body %}
    <pre>{{ orders_json | pprint }}</pre>
{% endblock %}