mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    MyLogoutView,
    get_cookie_view,
    set_cookie_view,
    get_session_view,
    set_session_view,
    AboutMeView,
    RegisterView,
    ProfilesListView,
    ProfileDetailView,
    ProfileUpdateView,
)

app_name = 'myauth'
urlpatterns = [
    path('profiles/', ProfilesListView.as_view(), name='profile_list'),
    path('profiles/<int:pk>/', ProfileDetailView.as_view(), name='profile_details'),
    path('profiles/<int:pk>/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path(
        'login/',
        LoginView.as_view(
            template_name='myauth/login.html',
            redirect_authenticated_user=True,
        ),
        name='login'
    ),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about_me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('cookie/get/', get_cookie_view, name='get_cookie'),
    path('cookie/set/', set_cookie_view, name='set_cookie'),
    path('session/get/', get_session_view, name='get_session'),
    path('session/set/', set_session_view, name='set_session'),
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def avatar_directory_path(instance: 'Profile', filename: str) -> str:
    return 'profiles/profile_{pk}/avatar/{filename}'.format(
        pk=instance.user.pk,
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=avatar_directory_path)

mysite/myauth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from .models import Profile
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin


class ProfilesListView(ListView):
    queryset = Profile.objects.select_related('user').order_by('user')
    context_object_name = 'profiles'


class ProfileDetailView(DetailView):
    queryset = Profile.objects.select_related('user')


class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        profile_owner = self.get_object().user
        return self.request.user.is_staff or profile_owner == self.request.user

    model = Profile
    fields = 'avatar', 'bio', 'agreement_accepted'
    template_name = 'myauth/profile-update.html'

    def get_success_url(self):
        return reverse(
            'myauth:profile_details',
            kwargs={'pk': self.object.pk},
        )


class AboutMeView(UpdateView):
    template_name = 'myauth/about-me.html'
    model = Profile
    fields = 'avatar',
    success_url = reverse_lazy('myauth:about_me')

    def get_object(self, queryset=None):
        # for Sentry verifying
        # 1 / 0
        # print(self.request.unknown_argument)
        # print(int('334f3'))
        if self.request.user.is_authenticated:
            obj = self.model.objects.get(pk=self.request.user.profile.pk)
            return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        current_profile = Profile.objects.get(user=self.object.user)
        current_profile.save()
        return response


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about_me')

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password1']
        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(self.request, user=user)
        return response


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('myauth:login')


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get('myuser', 'default cookie')
    return HttpResponse(f'Got cookie value: <i>{value}</i>')


def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse('<h2><i>Cookie set successfully!</i></h2>')
    response.set_cookie('myuser', 'mycookie', max_age=3600)
    return response


def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('myuser', 'default session')
    return HttpResponse(f'Got session value: <i>{value}</i>')


def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session['myuser'] = 'mysession'
    return HttpResponse(f'<h2><i>Session set successfully</i></h2>')

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <div>
            {% if object.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
            {% else %}
                <p><span style="font-size:x-large">No avatar uploaded yet</span></p>
            {% endif %}
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update profile picture</button>
        </form>

        <h2>User details:</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Biography: {{ user.profile.bio }}</p>
        <p><a href="{% url 'myauth:update_profile' pk=user.profile.pk %}">Update my profile</a></p>
    {% else %}
        <h2>Unknown user. <a href="{% url 'myauth:login' %}">Log in</a> for user info</h2>
    {% endif %}
    <p><a href="{% url 'myauth:profile_list' %}">View all profiles</a></p>

    <br>
    <div>
        <a href="{% url 'myauth:logout' %}">Logout</a>
    </div>
{% endblock %}

mysite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base.html title
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Base.html body
    {% endblock %}
</body>
</html>

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/profile-update.html
{% extends 'myauth/base.html' %}

{% block title %}
  Update profile
{% endblock %}

{% block body %}
  <h1>Update {{ object.user }}'s profile info</h1>
  <form method="post" enctype="multipart/form-data">
    {% if object.avatar %}
        <img src="{{ object.avatar.url }}" alt="{{ object.avatar.name }}">
    {% else %}
        <p><span style="font-size:x-large">No avatar uploaded yet</span></p>
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
      Update profile!
    </button>
  </form>

  <div>
    <a href="{% url 'myauth:profile_details' pk=object.pk %}">
      Click to return to the profile details
    </a>
  </div>

{% endblock %}

mysite/myauth/templates/myauth/profile_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
  {{ object.user }} details
{% endblock %}

{% block body %}
  <h1>{{ object.user }} profile details</h1>
  <div>
      <div>
          {% if object.avatar %}
              <img src="{{ object.avatar.url }}" alt="{{ object.avatar.name }}">
          {% else %}
              <p><span style="font-size:x-large">No avatar uploaded yet</span></p>
          {% endif %}
      </div>
    <div>Username: <code>{{ object.user }}</code></div>
    <div>First name: {% firstof object.user.first_name 'Not mentioned' %}</div>
    <div>Last name: {% firstof object.user.last_name 'Not mentioned' %}</div>
    <div>Bio: <i>{% firstof object.bio 'Not mentioned' %}</i></div>
    <div>User agreement accepted: <i>{{ object.agreement_accepted }}</i></div>
  </div>

  <br>
  {% if user.is_staff or user == object.user %}
    <div>
        <a href="{% url 'myauth:update_profile' pk=object.pk %}">Update this profile info</a>
    </div>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:orders_by_user' user_id=object.user.pk %}">See all this user's orders</a>
  </div>
  <div>
    <a href="{% url 'myauth:profile_list' %}">Back to the profiles list</a>
  </div>

{% endblock %}

mysite/myauth/templates/myauth/profile_list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Profiles list
{% endblock %}

{% block body %}
    <h1>List of existing accounts:</h1>
    <p><span style="font-size:x-large">
        <a href="{% url 'myauth:about_me' %}">Open my profile</a>
    </span></p>
    <div>
    <ul>
        {% for profile in profiles %}
            <li>
                <a href="{% url 'myauth:profile_details' pk=profile.pk %}">{{ profile.user }}</a>
            </li>
            {% if profile.bio %}
                <sub>-> {{ profile.bio }}</sub>
            {% else %}
                <sub>-- no bio --</sub>
            {% endif %}
        {% empty %}
            No accounts created yet
        {% endfor %}
    </ul>
    </div>

{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
    Registration
{% endblock %}

{% block body %}
    <h1>Register a new user</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}